
    create table Destination (
        id bigint generated by default as identity (start with 1),
        lowestPrice double,
        name varchar(255) not null,
        primary key (id),
        unique (name)
    );

    create table Hotel (
        id bigint generated by default as identity (start with 1),
        active boolean not null,
        lowestPrice double,
        name varchar(255) not null,
        destinationId bigint not null,
        primary key (id),
        unique (name)
    );

    create table Package (
        id bigint generated by default as identity (start with 1),
        active boolean not null,
        arrival timestamp not null,
        departure timestamp not null,
        price double not null,
        hotelId bigint not null,
        primary key (id)
    );

    alter table Hotel 
        add constraint FK42AD19433B9B256 
        foreign key (destinationId) 
        references Destination;

    alter table Package 
        add constraint FK331DCC26AE667F62 
        foreign key (hotelId) 
        references Hotel;
